/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
    "./node_modules/primevue/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'primary-50': 'rgb(var(--primary-50))',
        'primary-100': 'rgb(var(--primary-100))',
        'primary-200': 'rgb(var(--primary-200))',
        'primary-300': 'rgb(var(--primary-300))',
        'primary-400': 'rgb(var(--primary-400))',
        'primary-500': 'rgb(var(--primary-500))',
        'primary-600': 'rgb(var(--primary-600))',
        'primary-700': 'rgb(var(--primary-700))',
        'primary-800': 'rgb(var(--primary-800))',
        'primary-900': 'rgb(var(--primary-900))',
        'primary-950': 'rgb(var(--primary-950))',
        'surface-0': 'rgb(var(--surface-0))',
        'surface-50': 'rgb(var(--surface-50))',
        'surface-100': 'rgb(var(--surface-100))',
        'surface-200': 'rgb(var(--surface-200))',
        'surface-300': 'rgb(var(--surface-300))',
        'surface-400': 'rgb(var(--surface-400))',
        'surface-500': 'rgb(var(--surface-500))',
        'surface-600': 'rgb(var(--surface-600))',
        'surface-700': 'rgb(var(--surface-700))',
        'surface-800': 'rgb(var(--surface-800))',
        'surface-900': 'rgb(var(--surface-900))',
        'surface-950': 'rgb(var(--surface-950))',
        'transparent': 'transparent',
        'primary': '#000a65',
        'primary-variant': '#0a1679',
        'primary-tag': '#D0EEFF',
        'secondary': '#0019ff',
        'success': '#00a0a0',
        'text-primary': '#2e3d5a',
        'background': '#ebf3ff',
        'text-secondary': '#abb6c8',
        'danger-tag': '#FEEBEB',
        'danger': '#ff3535',
        'warning-tag': '#FFFBEB',
        'warning': '#D97706',
        'bg-input': '#f6f6f6',
        'placeholder': '#969696',
        'text-secondary-2': '#737e8d',
        'bg-card-2': '#d0e3ff',
        'pending': '#D0EEFF',
        'in-process': '#45A6FF',
        'finished': '#44C697',
        'tertiary': '#3758F9',
      }
    },
  },
  plugins: [],
}
